spring.application.name=booknest-emprestimo-ms
spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-server:8888}
spring.cloud.config.fail-fast=true
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
app.rabbitmq.consumidor.habilitado=${RABBITMQ_CONSUMIDOR_HABILITADO:true}
