spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/booknest_emprestimo}
spring.datasource.username=${DB_USERNAME:booknest}
spring.datasource.password=${DB_PASSWORD:booknest}
app.config.marker=local-dev
