spring.application.name=booknest-mit-arquitetura-ms-gustavo-figueiredo-api
spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-server:8888}
spring.cloud.config.fail-fast=true
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
