server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/booknest_emprestimo
spring.datasource.username=booknest
spring.datasource.password=booknest
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.rabbitmq.consumidor.habilitado=${RABBITMQ_CONSUMIDOR_HABILITADO:true}
app.config.marker=emprestimo-dev
