server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/booknest
spring.datasource.username=booknest
spring.datasource.password=booknest
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
servico.emprestimo.url=http://localhost:8081
app.config.marker=arquitetura-dev
