server.port=8081
spring.datasource.url=jdbc:postgresql://postgres-emprestimo:5432/booknest_emprestimo
spring.datasource.username=booknest
spring.datasource.password=booknest
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
app.config.marker=emprestimo-prod
